export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS="USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL="USER_UPDATE_FAIL"

export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL"

export const USER_LOADED_REQUEST="USER_LOADED_REQUEST"
export const USER_LOADED_SUCCESS="USER_LOADED_SUCCESS"
export const USER_LOADED_FAIL="USER_LOADED_FAIL"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAIL="LOGOUT_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET"

export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET="UPDATE_PASSWORD_RESET"

export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL"

export const NEW_PASSWORD_REQUEST="NEW_PASSWORD_REQUEST"
export const NEW_PASSWORD_SUCCESS="NEW_PASSWORD_SUCCESS"
export const NEW_PASSWORD_FAIL="NEW_PASSWORD_FAIL"